dist: trusty
sudo: required

language: python

python:
  - "3.6"

addons:
  apt:
    sources:
        - sourceline: "deb http://archive.ubuntu.com/ubuntu/ trusty multiverse"
        - sourceline: "deb http://archive.ubuntu.com/ubuntu/ trusty-updates multiverse"
    packages:
    - gstreamer1.0-plugins-base
    - gstreamer1.0-plugins-good
    - gstreamer1.0-plugins-bad
    - gstreamer1.0-plugins-ugly
    - gstreamer1.0-libav
    - gstreamer1.0-tools
    - python3-gst-1.0
    - python3-pip

virtualenv:
  system_site_packages: true

install:
  - pip3 install pyyaml gbulb sanic websockets psutil requests image

script:
  - pytest